version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
      args:
        - BACKEND_URL=http://backend:8000
        - API_SECRET=${API_SECRET}
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
      - API_SECRET=${API_SECRET}
    depends_on:
      - backend